Repository CodeitSB-Team9/sb01-deokhugam-team09, pull requests merged in 2025-04, with the labels that each got.

#8 [#7] Update issue templates
  .github/ISSUE_TEMPLATE/✨feature-issue-template.md
Labels: documentation

#10 [#9]📝 Docs ci workflow
  .github/ISSUE_TEMPLATE/✨feature-issue-template.md
  .github/workflows/ci-action.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: 📝문서 작업, 🐛버그 수정

#14 :memo: Docs: Create Dockerfile
  .dockerignore
  Dockerfile
  build.gradle
Labels: 📝문서 작업

#20 [#16] 도서 엔티티 설계
  build.gradle
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/entity/Book.java
Labels: ✨ 새 기능 추가

#17 [#15] 📝 Docs/readmd
  README.md
Labels: 📝문서 작업

#26 [#25] Feature: Create DDL script file
  src/main/resources/schema.sql
Labels: 📝문서 작업

#22 [#18] Docs/cd flow action 파일 생성
  .github/workflows/cd-action.yml
  ecs-task-definition.json
Labels: 📝문서 작업

#28 [#27] :sparkles: Feature: Create static file for view
  src/main/resources/static/favicon-32x32.png
  src/main/resources/static/images/book-placeholder.png
  src/main/resources/static/index-CngKKUej.js
  src/main/resources/static/index-D30UMZL2.css
  src/main/resources/static/index.html
Labels: ✨ 새 기능 추가

#29 🚀 Production Release
  .dockerignore
  .github/workflows/cd-action.yml
  .github/workflows/ci-action.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  ecs-task-definition.json
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/entity/Book.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/controller/CommentController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/dto/CommentDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/entity/Comment.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/exception/CommentException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/service/CommentService.java
  src/main/resources/schema.sql
  src/main/resources/static/favicon-32x32.png
  src/main/resources/static/images/book-placeholder.png
  src/main/resources/static/index-CngKKUej.js
  src/main/resources/static/index-D30UMZL2.css
  src/main/resources/static/index.html
Labels: ✨ 새 기능 추가

#33 :ambulance: Hotfix: CD flow 문제 병목지점 찾기 위해서 콘솔에 repo 주소 찍는 라인 추가
  .github/workflows/cd-action.yml
Labels: 🐛버그 수정

#34 :ambulance: Hotfix: CD flow 문제 병목지점 찾기, credential version 변경
  .github/workflows/cd-action.yml
Labels: 🐛버그 수정

#37 :ambulance: Hotfix: CD flow build flow에서 산출된 image 값을 출력하고 다음 단계에서 사용
  .github/workflows/cd-action.yml
Labels: 🐛버그 수정

#38 :ambulance: Hotfix: ECS 배포용 task definition 파일 재설정 (JSON 인코딩 문제 수정)
  .github/workflows/cd-action.yml
  ecs-task-definition.json
Labels: 🐛버그 수정

#39 :ambulance: Hotfix: ECS task definition 오류 수정 - enableFaultInjection 필드 제
  ecs-task-definition.json
Labels: 🐛버그 수정

#30 [#12] 유저 엔티티 설계
  build.gradle
  src/main/java/com/codeit/sb01_deokhugam/common/Period.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/PowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/entity/User.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/mapper/UserMapper.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
Labels: ✨ 새 기능 추가

#52 [#51] 공통 기능: PageResponse 추가
  src/main/java/com/codeit/sb01_deokhugam/global/dto/response/PageResponse.java
Labels: ✨ 새 기능 추가

#54 [#42] User 요청/응답 DTO 설계
  src/main/java/com/codeit/sb01_deokhugam/common/Period.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/PowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/UserUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/CursorPageResponsePowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/PowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/UserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/mapper/UserMapper.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
Labels: ✨ 새 기능 추가

#64 [#63] :ambulance: Hotfix:CI 빌드 시점에 환경변수 설정
  .github/workflows/ci-action.yml
Labels: 🐛버그 수정

#62 [#57] Feat: S3 이미지 업로드 기능 구현 및 테스트 완료
  .gitattributes
  build.gradle
  ecs-task-definition.json
  src/main/java/com/codeit/sb01_deokhugam/config/S3Configuration.java
  src/main/java/com/codeit/sb01_deokhugam/global/s3/S3Service.java
  src/main/resources/application.yml
Labels: ✨ 새 기능 추가

#67 [#66] 페이지네이션-QueryDsl 관련 설정
  .gitignore
  build.gradle
  src/main/java/com/codeit/sb01_deokhugam/config/QueryDslConfig.java
Labels: ✨ 새 기능 추가

#68 [#57] ✨ S3 파일 업로드 기능 및 예외 처리 로직 추가
  src/main/java/com/codeit/sb01_deokhugam/config/S3Configuration.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/sb01_deokhugam/global/s3/S3Service.java
  src/main/java/com/codeit/sb01_deokhugam/global/s3/exception/S3UploadException.java
Labels: ✨ 새 기능 추가

#70 [#53] User 관련 기능, 예외 추가
  src/main/java/com/codeit/sb01_deokhugam/domain/user/controller/UserController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/CursorPageResponsePowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/UserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/entity/User.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/exception/InvalidCredentialsException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/exception/UserException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/exception/UserNotFoundException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/AuthService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicAuthService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
  src/main/java/com/codeit/sb01_deokhugam/global/enumType/Period.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
Labels: ✨ 새 기능 추가

#74 ✨[#69] Feature: 알림 엔티티 매핑, 생성 정적 메서드 생
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/entity/Notification.java
  src/main/resources/schema.sql
Labels: ✨ 새 기능 추가

#78 [#75] ✨ feat: 로그인 사용자 ID 추출 리졸버 및 알림 상태 변경 API 구현
  src/main/java/com/codeit/sb01_deokhugam/auth/exception/LoginRequiredException.java
  src/main/java/com/codeit/sb01_deokhugam/config/WebConfiguration.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/dto/request/NotificationUpdateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/dto/response/NotificationDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/exception/NotificationException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/sb01_deokhugam/global/resolver/LoginUserIdArgumentResolver.java
  src/main/java/com/codeit/sb01_deokhugam/global/resolver/annotation/LoginUserId.java
Labels: ✨ 새 기능 추가

#80 [#79] ✅ Test Notification 읽음 상태 변경 테스트
  build.gradle
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/entity/Comment.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/entity/Review.java
  src/main/java/com/codeit/sb01_deokhugam/global/resolver/LoginUserIdArgumentResolver.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/codeit/sb01_deokhugam/util/TestUtils.java
Labels: ✅테스트 코드 작업

#88 [#85] ✨ 운영 환경 배포를 위한 ECS 환경변수 및 CD 파이프라인 설정
  .github/workflows/cd-action.yml
  .github/workflows/ci-action.yml
  build.gradle
  ecs-task-definition.json
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: ✨ 새 기능 추가

#90 🚑 [FIX] dev → main 병합 충돌 해결 PR
  .github/workflows/cd-action.yml
Labels: 🐛버그 수정

#97 🚑 [Hotfix] ECS CD 자동화 설정 및 TaskDefinition 구조 정리
  .dockerignore
  .github/ecs/ecs-task-definition.json
  .github/workflows/cd-action.yml
  build.gradle
  ecs-task-definition.json
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🐛버그 수정

#99 [#75] Feature, Test 알림 전체 읽음 처리 기능
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ 새 기능 추가, ✅테스트 코드 작업

#91 [#72 / #81] 유저 관련 컨트롤러 추가, 디렉터리 구조 개선, 파워유저 관련 도메인 분리 등
  src/main/java/com/codeit/sb01_deokhugam/auth/controller/AuthController.java
  src/main/java/com/codeit/sb01_deokhugam/auth/exception/InvalidCredentialsException.java
  src/main/java/com/codeit/sb01_deokhugam/auth/request/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/auth/service/AuthService.java
  src/main/java/com/codeit/sb01_deokhugam/auth/service/BasicAuthService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/controller/UserController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/CursorPageResponsePowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/response/PowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/entity/User.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/mapper/UserMapper.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/controller/PowerUserController.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/dto/request/GetPowerUsersRequest.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/dto/response/PowerUserDto.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/entity/PowerUser.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/mapper/PowerUserMapper.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepository.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepositoryCustomImpl.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/BasicPowerUserService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/PowerUserService.java
  src/main/resources/schema.sql
Labels: ✨ 새 기능 추가

#104 [#75, 76] ✨ feat: 커서 기반 알림 조회 기능 구현 및 예외 처리, 테스트 추가
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/dto/request/NotificationSearchCondition.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/CursorNotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/custom/CursorNotificationRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/global/dto/response/PageResponse.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
  src/main/resources/data.sql
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/codeit/sb01_deokhugam/util/EntityProvider.java
Labels: ✨ 새 기능 추가, ✅테스트 코드 작업
