Repository CodeitSB-Team9/sb01-deokhugam-team09, pull requests merged in 2025-05, with the labels that each got.

#107 [#106] Jacoco 테스트 커버리지 설정
  .github/workflows/ci-action.yml
  build.gradle
Labels: ✨ 새 기능 추가

#108 [#105] ✨ Feature: 확인된 알림 중 일주일 이상 지난 데이터 삭제 기능 추가
  src/main/java/com/codeit/sb01_deokhugam/config/SchedulingConfiguration.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/custom/CursorNotificationRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
  src/main/resources/data.sql
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepositoryTest.java
Labels: ✨ 새 기능 추가, ✅테스트 코드 작업

#112 [#96] 유저 컨트롤러 테스트 코드 작성
  src/main/java/com/codeit/sb01_deokhugam/auth/controller/AuthController.java
  src/main/java/com/codeit/sb01_deokhugam/auth/exception/AccessDeniedException.java
  src/main/java/com/codeit/sb01_deokhugam/auth/request/UserLoginRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/controller/UserController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/ValidationSequence.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/entity/User.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/ErrorCode.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/entity/PowerUser.java
  src/test/java/com/codeit/sb01_deokhugam/auth/controller/AuthControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/ranking/poweruser/controller/PowerUserControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/util/EntityProvider.java
Labels: ✅테스트 코드 작업

#114 [#95] 인기 도서 랭킹 배치 스케줄링 코드 작성 및 도서 스케줄러 테스트코드 작성
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookRankingCalculation.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/entity/Book.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookRankingScheduler.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/global/schedule/utils/ScheduleUtils.java
  src/main/resources/data.sql
  src/test/java/com/codeit/sb01_deokhugam/domain/book/repository/BookRepositoryTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/book/service/BookRankingSchedulerTest.java
Labels: ✨ 새 기능 추가, ✅테스트 코드 작업

#115 [#109] Actuator 의존성 추가, 환경설정
  .github/workflows/ci-action.yml
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/yaml/actuator/actuator.yml
Labels: ✨ 새 기능 추가, 🐛버그 수정

#116 [#113] 유저 컨트롤러 테스트 코드 작성
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/UserService.java
  src/main/resources/data.sql
  src/test/java/com/codeit/sb01_deokhugam/auth/service/BasicAuthServiceTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserServiceTest.java
Labels: ✅테스트 코드 작업

#120 :sparkles: 엔티티 클래스에 있는 인덱스 기반으로 sql 추가
  src/main/resources/schema.sql
Labels: 📝문서 작업

#121 [#111] 도서 서비스 코드 일부, MDC & 응답헤더& 로그에 요청 id & IP 추가
  src/main/java/com/codeit/sb01_deokhugam/config/WebConfiguration.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/controller/BookController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/NaverBookDto.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/repository/BookRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookRankingScheduler.java
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookService.java
  src/main/java/com/codeit/sb01_deokhugam/global/intercepter/MdcLoggingIntercepter.java
  src/main/java/com/codeit/sb01_deokhugam/global/naver/NaverBookClient.java
  src/main/resources/data.sql
  src/main/resources/logback.xml
  src/test/java/com/codeit/sb01_deokhugam/domain/book/service/BookServiceTest.java
Labels: ✨ 새 기능 추가, ✅테스트 코드 작업

#124 [#117] 파워유저 랭킹 계산 기능 레포지토리 구현
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/controller/PowerUserController.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserCalculationRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserCalculationRepositoryCustomImpl.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepositoryCustomImpl.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/BasicPowerUserService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/RankingCalculationService.java
  src/main/resources/data.sql
Labels: ✨ 새 기능 추가

#128 Docs/readme 사용한 기술 스택 정리
  README.md
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/service/CommentService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/service/NotificationService.java
Labels: 📝문서 작업

#133 [#111] MDC uri추가, 도서 서비스 테스트 코드 일부 작성
  src/main/java/com/codeit/sb01_deokhugam/domain/book/dto/BookCreateRequest.java
  src/main/java/com/codeit/sb01_deokhugam/global/intercepter/MdcLoggingIntercepter.java
  src/main/resources/logback.xml
  src/test/java/com/codeit/sb01_deokhugam/domain/book/service/BookServiceTest.java
  src/test/java/com/codeit/sb01_deokhugam/util/EntityProvider.java
Labels: ✨ 새 기능 추가, 🐛버그 수정, ✅테스트 코드 작업

#132 Fix: 서버 Alpine 이미지 버전 내부에 ocr에러 수정을 위해 다운로드 추가
  Dockerfile
Labels: 🐛버그 수정

#136 [#117] 파워유저 컨트롤러 오류 수정
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/repository/CommentRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/notification/repository/NotificationRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewLikeRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/PopularReviewBatchService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/controller/UserController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserService.java
  src/main/java/com/codeit/sb01_deokhugam/global/exception/GlobalExceptionHandler.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/controller/PowerUserController.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserCalculationRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserCalculationRepositoryCustomImpl.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRankingRepository.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepository.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserSearchRepository.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/repository/PowerUserSearchRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/BasicPowerUserCalculationService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/BasicPowerUserService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/PowerUserCalculationService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/PowerUserService.java
  src/main/java/com/codeit/sb01_deokhugam/ranking/poweruser/service/RankingCalculationService.java
  src/main/resources/data.sql
  src/test/java/com/codeit/sb01_deokhugam/domain/user/controller/UserControllerTest.java
  src/test/java/com/codeit/sb01_deokhugam/domain/user/service/BasicUserServiceTest.java
  src/test/java/com/codeit/sb01_deokhugam/ranking/poweruser/controller/PowerUserControllerTest.java
Labels: 🐛버그 수정, ✅테스트 코드 작업

#139 :sparkles: feat: Refactor overall structure of review domain for prod…
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/service/CommentService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/entity/Review.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/entity/ReviewLike.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/entity/ReviewRanking.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/mapper/ReviewMapper.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewLikeRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/ReviewService.java
  src/main/resources/schema.sql
Labels: ✨ 새 기능 추가, 🐛버그 수정

#143 :ambulance: fix: 전반적 실서비스 버그 수정, n+1 최적화
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/service/CommentService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/ReviewService.java
Labels: 🐛버그 수정

#141 Fix 배포시 배치 시간 수정
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookRankingScheduler.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/PopularReviewBatchService.java
  src/main/java/com/codeit/sb01_deokhugam/global/schedule/utils/ScheduleUtils.java
Labels: 🐛버그 수정

#144 기능 업데이트 후 재배포
  src/main/java/com/codeit/sb01_deokhugam/domain/book/service/BookRankingScheduler.java
  src/main/java/com/codeit/sb01_deokhugam/domain/comment/service/CommentService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/controller/ReviewController.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/PopularReviewRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepository.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/PopularReviewBatchService.java
  src/main/java/com/codeit/sb01_deokhugam/domain/review/service/ReviewService.java
  src/main/java/com/codeit/sb01_deokhugam/global/schedule/utils/ScheduleUtils.java
Labels: :rocket: 배포

#149 🐛 OCR 버그 수정
  src/main/java/com/codeit/sb01_deokhugam/domain/book/controller/BookController.java
Labels: 🐛버그 수정

#154 fix : OCR tessdata 폴터 환경변수 위치 변경 - 폴더 변경
  Dockerfile
Labels: 🐛버그 수정

#155 Docs : 리드미 아키텍처, ERD, 오타 수정
  README.md
Labels: 📝문서 작업
